/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import views.panels.NavigationPanel;

/**
 *
 * @author Raphael
 */
public class MainView extends javax.swing.JPanel {
    public static CardLayout mainViewCardLayout;
    public static JPanel viewStudents;
    public static JPanel viewEmployees;
    public static JPanel viewDashboard;
    public static ViewGrading viewGrading;
    public static ViewColleges viewColleges;
    public static ViewCourses viewCourses;
    public static JPanel viewSubjects;
    public static ViewSettings viewSettings;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        navigationItems.add(NavigationPanel.createNavigationPanel());
        
        viewDashboard = new ViewDashboard();
        viewStudents = new ViewStudents();
        viewEmployees = new ViewEmployees();
        viewGrading = new ViewGrading();
        viewColleges = new ViewColleges();
        viewCourses = new ViewCourses();
        viewSettings = new ViewSettings();
        viewSubjects = new ViewSubjects();
        
        viewsPanel.add(viewDashboard, "viewDashboard");
        viewsPanel.add(viewStudents, "viewStudents");
        viewsPanel.add(viewEmployees, "viewEmployees");
        viewsPanel.add(viewGrading, "viewGrading");
        viewsPanel.add(viewColleges, "viewColleges");
        viewsPanel.add(viewCourses, "viewCourses");
        viewsPanel.add(viewSettings, "viewSettings");
        viewsPanel.add(viewSubjects, "viewSubjects");
        
        mainViewCardLayout = (CardLayout) viewsPanel.getLayout();
        
        NavigationPanel.dashboardItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mainViewCardLayout.show(viewsPanel, "viewDashboard");
            }
        });
        NavigationPanel.studentItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                ViewStudents.studListPanel.refreshData(false);
                mainViewCardLayout.show(viewsPanel, "viewStudents");
            }
        });
        NavigationPanel.employeesItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                ViewEmployees.empListPanel.refreshData(false);
                mainViewCardLayout.show(viewsPanel, "viewEmployees");
            }
        });
        NavigationPanel.gradingItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                viewGrading.refreshData();
                viewGrading.refreshComboBox();
                mainViewCardLayout.show(viewsPanel, "viewGrading");
            }
        });
        NavigationPanel.collegesItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                viewColleges.refreshData();
                mainViewCardLayout.show(viewsPanel, "viewColleges");
            }
        });
        NavigationPanel.settingsItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                viewSettings.refreshData();
                mainViewCardLayout.show(viewsPanel, "viewSettings");
            }
        });
        NavigationPanel.coursesItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                viewCourses.refreshData();
                mainViewCardLayout.show(viewsPanel, "viewCourses");
            }
        });
        NavigationPanel.subjectsItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                ViewSubjects.subListPanel.refreshData();
                mainViewCardLayout.show(viewsPanel, "viewSubjects");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        navigationItems = new javax.swing.JPanel();
        viewsPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(250, 250, 250));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        navigationPanel.setBackground(new java.awt.Color(255, 255, 255));
        navigationPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 30, 30, 30));
        navigationPanel.setLayout(new java.awt.BorderLayout(0, 20));

        lblAppName.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        lblAppName.setText("🥲✅ App Name");
        lblAppName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        navigationPanel.add(lblAppName, java.awt.BorderLayout.PAGE_START);

        navigationItems.setBackground(new java.awt.Color(255, 255, 255));
        navigationItems.setLayout(new javax.swing.BoxLayout(navigationItems, javax.swing.BoxLayout.Y_AXIS));
        navigationPanel.add(navigationItems, java.awt.BorderLayout.CENTER);

        viewsPanel.setBackground(new java.awt.Color(250, 250, 250));
        viewsPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(viewsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAppName;
    private javax.swing.JPanel navigationItems;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPanel viewsPanel;
    // End of variables declaration//GEN-END:variables
}
