/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.CardLayout;
import javax.swing.JLayeredPane;

/**
 *
 * @author Raphael
 */
public class ViewEmployees extends javax.swing.JPanel {
    public static CardLayout viewEmployeesCardLayout;
    public static EmployeesInfo empInfoPanel;
    public static EmployeesList empListPanel;
    
    /**
     * Creates new form ViewStudents
     */
    public ViewEmployees() {
        initComponents();
        
        viewEmployeesCardLayout = (CardLayout) getLayout();
        empListPanel = new EmployeesList();
        empInfoPanel = new EmployeesInfo();
        
        add(empInfoPanel, "empInfoPanel");
        add(empListPanel, "empListPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(1030, 720));
        setMinimumSize(new java.awt.Dimension(1030, 720));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1030, 720));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
